services:
  app:
    build: .
    container_name: lab309-sse-app
    ports:
      - "8080:8080"
    environment:
      # MQTT - kết nối tới EMQX chạy trên host machine
      MQTT_BROKER_URL: ws://host.docker.internal:8083/mqtt
      MQTT_CLIENT_ID: lab309-sse-publisher
      MQTT_SUBSCRIBER_CLIENT_ID: lab309-sse-subscriber
      MQTT_TOPIC: /test/topic
      MQTT_SUBSCRIBE_TOPICS: /test/topic
